name: Deploy neeiz-app to CapRover

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'packages/**'
      - 'pnpm-workspace.yaml'
      - '.github/workflows/deploy-app.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build application
        run: pnpm run build

      - name: Create deployment tar (include workspace packages)
        run: |
          # Create a clean directory for deployment
          mkdir -p ../deploy_temp
          # Copy app sources
          cp -r . ../deploy_temp/
          # Include workspace files needed for workspace:* deps
          cp -r ../packages ../deploy_temp/packages
          cp ../pnpm-workspace.yaml ../deploy_temp/pnpm-workspace.yaml
          cd ../deploy_temp
          
          # Remove unnecessary files
          rm -rf node_modules .git dist .pnpm-store .DS_Store
          
          # Create tar file in the workspace root where CapRover expects it
          tar -czf ../deploy.tar .
          cd ..
          rm -rf deploy_temp

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: 'neeiz-app'
          token: '${{ secrets.CAPROVER_NEEIZ_APP_TOKEN }}'
