name: Deploy neeiz-api to CapRover

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - 'packages/**'
      - 'pnpm-workspace.yaml'
      - '.github/workflows/deploy-api.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build application
        run: pnpm run build

      - name: Create deployment tar (include workspace packages)
        run: |
          mkdir -p ../deploy_temp
          cp -r . ../deploy_temp/
          # copy workspace root files and packages into app build context dir
          cp -r ../packages ../deploy_temp/packages
          cp ../pnpm-workspace.yaml ../deploy_temp/pnpm-workspace.yaml
          cd ../deploy_temp
          rm -rf node_modules .git dist .pnpm-store .DS_Store
          tar -czf ../deploy.tar .
          cd ..
          rm -rf deploy_temp

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: 'neeiz-api'
          token: '${{ secrets.CAPROVER_NEEIZ_API_TOKEN }}'